### PR TITLE
Update so ESP3DLib is compatible with Marlin bugfix  

### PR DESCRIPTION
**Pull request by ellensp**
Includes U8glib-HAL.h vs U8glib wen it should
updated SERIAL_ECHOLN to SERIAL_ECHOLNPGM
Added some indenting for readability

### CODE REVIEW

**Comment by luc-github** [comment]
Thank you - is that also compatible with latest release ?

**Comment by ellensp** [comment]
I only targeted bugfix, but yes a quick test and yes it compiles with 2.0.9.3 also.

**Comment by luc-github** [comment]
Thank you - hopefuly in next version it should not be needed anymore

**Comment by luc-github** [comment]
@all-contributors please add @ellensp for bug fix

**Pull request merged**
